# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BufferWithoutOverlaps
                                 A QGIS plugin
 This plugin creates a buffer around features of given type, without overlaps and with flat end caps.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-20
        copyright            : (C) 2022 by António Sobral Almeida
        email                : sobral.almeida@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'António Sobral Almeida'
__date__ = '2022-03-20'
__copyright__ = '(C) 2022 by António Sobral Almeida'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BufferWithoutOverlaps class from file BufferWithoutOverlaps.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .buffer_without_overlaps import BufferWithoutOverlapsPlugin
    return BufferWithoutOverlapsPlugin()
